In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded = files.upload()

Saving home_data.csv to home_data.csv

In [7]:
df.hd = pd.read_csv('home_data.csv')
print(df.hd.head(5))

           id             date  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  7129300520  20141013T000000         3       1.00         1180      5650
1  6414100192  20141209T000000         3       2.25         2570      7242
2  5631500400  20150225T000000         2       1.00          770     10000
3  2487200875  20141209T000000         4       3.00         1960      5000
4  1954400510  20150218T000000         3       2.00         1680      8080

   floors  waterfront  view  condition  grade  sqft_above  sqft_basement  \
0     1.0           0     0          3      7        1180              0
1     2.0           0     0          3      7        2170            400
2     1.0           0     0          3      6         770              0
3     1.0           0     0          5      7        1050            910
4     1.0           0     0          3      8        1680              0

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340
1      1951          1991    98125  47.7210 -122.319           1690
2      1933             0    98028  47.7379 -122.233           2720
3      1965             0    98136  47.5208 -122.393           1360
4      1987             0    98074  47.6168 -122.045           1800

   sqft_lot15
0        5650
1        7639
2        8062
3        5000
4        7503

In [4]:
from google.colab import files
uploaded = files.upload()

Saving home_prices.csv to home_prices.csv

In [8]:
df.hp = pd.read_csv('home_prices.csv')
print(df.hp.head(5))

     house_id   price
0  7129300520  221900
1  6414100192  538000
2  5631500400  180000
3  2487200875  604000
4  1954400510  510000

<ipython-input-8-2cf44a414b9b>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.hp = pd.read_csv('home_prices.csv')

In [17]:
df = pd.merge(df.hd, df.hp, left_on='id', right_on='house_id')
print(df.head(5))

           id             date  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  7129300520  20141013T000000         3       1.00         1180      5650
1  6414100192  20141209T000000         3       2.25         2570      7242
2  5631500400  20150225T000000         2       1.00          770     10000
3  2487200875  20141209T000000         4       3.00         1960      5000
4  1954400510  20150218T000000         3       2.00         1680      8080

   floors  waterfront  view  condition  ...  sqft_basement  yr_built  \
0     1.0           0     0          3  ...              0      1955
1     2.0           0     0          3  ...            400      1951
2     1.0           0     0          3  ...              0      1933
3     1.0           0     0          5  ...            910      1965
4     1.0           0     0          3  ...              0      1987

   yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0             0    98178  47.5112 -122.257           1340        5650
1          1991    98125  47.7210 -122.319           1690        7639
2             0    98028  47.7379 -122.233           2720        8062
3             0    98136  47.5208 -122.393           1360        5000
4             0    98074  47.6168 -122.045           1800        7503

     house_id   price
0  7129300520  221900
1  6414100192  538000
2  5631500400  180000
3  2487200875  604000
4  1954400510  510000

[5 rows x 22 columns]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21969 entries, 0 to 21968
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21969 non-null  int64
 1   date           21969 non-null  object
 2   bedrooms       21969 non-null  int64
 3   bathrooms      21969 non-null  float64
 4   sqft_living    21969 non-null  int64
 5   sqft_lot       21969 non-null  int64
 6   floors         21969 non-null  float64
 7   waterfront     21969 non-null  int64
 8   view           21969 non-null  int64
 9   condition      21969 non-null  int64
 10  grade          21969 non-null  int64
 11  sqft_above     21969 non-null  int64
 12  sqft_basement  21969 non-null  int64
 13  yr_built       21969 non-null  int64
 14  yr_renovated   21969 non-null  int64
 15  zipcode        21969 non-null  int64
 16  lat            21969 non-null  float64
 17  long           21969 non-null  float64
 18  sqft_living15  21969 non-null  int64
 19  sqft_lot15     21969 non-null  int64
 20  house_id       21969 non-null  int64
 21  price          21969 non-null  int64
dtypes: float64(4), int64(17), object(1)
memory usage: 3.7+ MB

In [20]:
df.describe()

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,house_id,price
count,2.196900e+04,21969.000000,21969.000000,21969.000000,2.196900e+04,21969.000000,21969.000000,21969.000000,21969.000000,21969.000000,...,21969.000000,21969.000000,21969.000000,21969.000000,21969.000000,21969.000000,21969.000000,21969.000000,2.196900e+04,2.196900e+04
mean,4.579052e+09,3.369384,2.109598,2074.334426,1.505021e+04,1.490578,0.007420,0.232692,3.407438,7.647139,...,291.023032,1970.821157,83.755383,98078.099276,47.559845,-122.214296,1983.030771,12733.700396,4.579052e+09,5.380970e+05
std,2.876614e+09,0.931695,0.770664,917.044924,4.118718e+04,0.539185,0.085819,0.764770,0.651837,1.177961,...,442.159118,29.348721,400.189783,53.578651,0.138485,0.140693,684.801400,27163.313081,2.876614e+09,3.663890e+05
min,1.000102e+06,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,1.000102e+06,7.500000e+04
25%,2.122059e+09,3.000000,1.500000,1420.000000,5.050000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,...,0.000000,1951.000000,0.000000,98033.000000,47.470500,-122.329000,1480.000000,5100.000000,2.122059e+09,3.200000e+05
50%,3.904940e+09,3.000000,2.250000,1910.000000,7.620000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,...,0.000000,1974.000000,0.000000,98065.000000,47.571200,-122.231000,1830.000000,7620.000000,3.904940e+09,4.500000e+05
75%,7.309100e+09,4.000000,2.500000,2540.000000,1.067500e+04,2.000000,0.000000,0.000000,4.000000,8.000000,...,560.000000,1996.000000,0.000000,98118.000000,47.677900,-122.126000,2360.000000,10080.000000,7.309100e+09,6.410000e+05
max,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,...,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,9.900000e+09,7.700000e+06

In [21]:
df.drop('house_id', axis=1, inplace=True)

In [22]:
df.head(5)

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
0,7129300520,20141013T000000,3,1.00,1180,5650,1.0,0,0,3,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,221900
1,6414100192,20141209T000000,3,2.25,2570,7242,2.0,0,0,3,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,538000
2,5631500400,20150225T000000,2,1.00,770,10000,1.0,0,0,3,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,180000
3,2487200875,20141209T000000,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,604000
4,1954400510,20150218T000000,3,2.00,1680,8080,1.0,0,0,3,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,510000

In [23]:
df.isna()

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21964,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21965,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21966,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21967,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21968,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [25]:
df.date = pd.to_datetime(df.date)
df.date.info()

<class 'pandas.core.series.Series'>
RangeIndex: 21969 entries, 0 to 21968
Series name: date
Non-Null Count  Dtype
--------------  -----
21969 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 171.8 KB

In [26]:
price_grade_df = df.groupby('grade')['price'].mean()
print(price_grade_df)

grade
1     1.420000e+05
3     2.056667e+05
4     2.143810e+05
5     2.468467e+05
6     3.000074e+05
7     4.020917e+05
8     5.425189e+05
9     7.739818e+05
10    1.072247e+06
11    1.494434e+06
12    2.169810e+06
13    3.709615e+06
Name: price, dtype: float64

In [28]:
df[df.condition > 3]

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
3,2487200875,2014-12-09,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,604000
11,9212900260,2014-05-27,2,1.00,1160,6000,1.0,0,0,4,...,860,300,1942,0,98115,47.6900,-122.292,1330,6000,468000
12,114101516,2014-05-28,3,1.00,1430,19901,1.5,0,0,4,...,1430,0,1927,0,98028,47.7558,-122.229,1780,12697,310000
13,6054650070,2014-10-07,3,1.75,1370,9680,1.0,0,0,4,...,1370,0,1977,0,98074,47.6127,-122.045,1370,10208,400000
17,6865200140,2014-05-29,4,1.00,1600,4300,1.5,0,0,4,...,1600,0,1916,0,98103,47.6648,-122.343,1610,4300,485000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21433,3449000010,2015-03-12,3,1.00,1140,8400,1.0,0,0,4,...,1140,0,1960,0,98059,47.5022,-122.144,1400,9000,294570
21566,7234600098,2014-09-05,3,3.00,1330,1379,2.0,0,0,4,...,1120,210,2005,0,98122,47.6126,-122.313,1810,1770,552100
21657,522059130,2015-04-29,3,1.00,1150,18200,1.0,0,0,5,...,1150,0,1959,0,98058,47.4262,-122.187,1714,18200,465000
21686,9266700190,2015-05-11,1,1.00,390,2000,1.0,0,0,4,...,390,0,1920,0,98103,47.6938,-122.347,1340,5100,245000
21939,2025049203,2014-06-10,2,1.00,710,1157,2.0,0,0,4,...,710,0,1943,0,98102,47.6413,-122.329,1370,1173,399950

In [29]:
df[df.price < 2000000]

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
0,7129300520,2014-10-13,3,1.00,1180,5650,1.0,0,0,3,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,221900
1,6414100192,2014-12-09,3,2.25,2570,7242,2.0,0,0,3,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,538000
2,5631500400,2015-02-25,2,1.00,770,10000,1.0,0,0,3,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,180000
3,2487200875,2014-12-09,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,604000
4,1954400510,2015-02-18,3,2.00,1680,8080,1.0,0,0,3,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,510000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21964,263000018,2014-05-21,3,2.50,1530,1131,3.0,0,0,3,...,1530,0,2009,0,98103,47.6993,-122.346,1530,1509,360000
21965,6600060120,2015-02-23,4,2.50,2310,5813,2.0,0,0,3,...,2310,0,2014,0,98146,47.5107,-122.362,1830,7200,400000
21966,1523300141,2014-06-23,2,0.75,1020,1350,2.0,0,0,3,...,1020,0,2009,0,98144,47.5944,-122.299,1020,2007,402101
21967,291310100,2015-01-16,3,2.50,1600,2388,2.0,0,0,3,...,1600,0,2004,0,98027,47.5345,-122.069,1410,1287,400000
21968,1523300157,2014-10-15,2,0.75,1020,1076,2.0,0,0,3,...,1020,0,2008,0,98144,47.5941,-122.299,1020,1357,325000

In [31]:
home_price_condition_df = df[(df.condition > 3) & (df.price < 2000000)]
print(home_price_condition_df)

               id       date  bedrooms  bathrooms  sqft_living  sqft_lot  \
3      2487200875 2014-12-09         4       3.00         1960      5000
11     9212900260 2014-05-27         2       1.00         1160      6000
12      114101516 2014-05-28         3       1.00         1430     19901
13     6054650070 2014-10-07         3       1.75         1370      9680
17     6865200140 2014-05-29         4       1.00         1600      4300
...           ...        ...       ...        ...          ...       ...
21433  3449000010 2015-03-12         3       1.00         1140      8400
21566  7234600098 2014-09-05         3       3.00         1330      1379
21657   522059130 2015-04-29         3       1.00         1150     18200
21686  9266700190 2015-05-11         1       1.00          390      2000
21939  2025049203 2014-06-10         2       1.00          710      1157

       floors  waterfront  view  condition  ...  sqft_above  sqft_basement  \
3         1.0           0     0          5  ...        1050            910
11        1.0           0     0          4  ...         860            300
12        1.5           0     0          4  ...        1430              0
13        1.0           0     0          4  ...        1370              0
17        1.5           0     0          4  ...        1600              0
...       ...         ...   ...        ...  ...         ...            ...
21433     1.0           0     0          4  ...        1140              0
21566     2.0           0     0          4  ...        1120            210
21657     1.0           0     0          5  ...        1150              0
21686     1.0           0     0          4  ...         390              0
21939     2.0           0     0          4  ...         710              0

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
3          1965             0    98136  47.5208 -122.393           1360
11         1942             0    98115  47.6900 -122.292           1330
12         1927             0    98028  47.7558 -122.229           1780
13         1977             0    98074  47.6127 -122.045           1370
17         1916             0    98103  47.6648 -122.343           1610
...         ...           ...      ...      ...      ...            ...
21433      1960             0    98059  47.5022 -122.144           1400
21566      2005             0    98122  47.6126 -122.313           1810
21657      1959             0    98058  47.4262 -122.187           1714
21686      1920             0    98103  47.6938 -122.347           1340
21939      1943             0    98102  47.6413 -122.329           1370

       sqft_lot15   price
3            5000  604000
11           6000  468000
12          12697  310000
13          10208  400000
17           4300  485000
...           ...     ...
21433        9000  294570
21566        1770  552100
21657       18200  465000
21686        5100  245000
21939        1173  399950

[7399 rows x 21 columns]

In [32]:
price_yr_built_df = df.groupby('yr_built')['price'].min()
print(price_yr_built_df)

yr_built
1900    130000
1901    285000
1902    260000
1903    167500
1904    204995
         ...
2011    249000
2012    160797
2013    155000
2014    175003
2015    230000
Name: price, Length: 116, dtype: int64

In [33]:
df.drop('sqft_living15', axis=1, inplace=True)

In [34]:
df.drop('waterfront', axis=1, inplace=True)

In [35]:
homes_df_merged = df
homes_df_merged.head(3)

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_lot15,price
0,7129300520,2014-10-13,3,1.00,1180,5650,1.0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,5650,221900
1,6414100192,2014-12-09,3,2.25,2570,7242,2.0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,7639,538000
2,5631500400,2015-02-25,2,1.00,770,10000,1.0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,8062,180000

In [36]:
homes_pivot_table = homes_df_merged.pivot_table(values='sqft_living', index='floors', aggfunc='mean')
print(homes_pivot_table)

        sqft_living
floors
1.0     1727.755126
1.5     1903.158649
2.0     2570.590126
2.5     3145.428571
3.0     1787.641815
3.5     2518.000000